version: 0.2
env:
  variables:
    DB_HOST: $DB_HOST
    USERNAME: $USERNAME
    PASSWORD: $PASSWORD
    DATABASE: $DATABASE
    TOKEN_SECRET: $TOKEN_SECRET
    NODE_ENV: $NODE_ENV
phases:
  install:
    commands:
      - git config --global credential.helper '!aws --region us-east-1 codecommit credential-helper $@'
      - git config --global credential.UseHttpPath true
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - sam --version
      - npm install
      - npm install --location=global cross-env cross-var-no-babel
  build:
    commands:
      - npm run deploy-production
